INSERT INTO diccionario (nombre, descripcion, tipo) VALUES
('Diccionario de la lengua española', 'El Diccionario de la lengua española es el resultado de la colaboración de todas las academias, cuyo propósito es recoger el léxico general utilizado en España y en los países hispánicos. Se dirige, fundamentalmente, a hablantes cuya lengua materna es el español, quienes encontrarán en él recursos suficientes para descifrar textos escritos y orales.', 'Normativo'),
('Diccionario de uso del español', 'Para guiar en el uso del español tanto a los que lo tienen como idioma propio como a aquellos que lo aprenden y han llegado en el conocimiento de él a ese punto en que el diccionario bilingüe puede y debe ser sustituido por el diccionario en el propio idioma que se aprende. Y ello, en primer lugar, trayendo a la mano del usuario todos los recursos de que el idioma dispone para nombrar una cosa, para expresar una idea con la máxima precisión o para realizar verbalmente cualquier acto expresivo. Y, en segundo lugar, resolviendo sus dudas acerca de la legitimidad o ilegitimidad de una expresión, de la manera correcta de resolver cierto caso de construcción, etc.', 'De uso práctico');

INSERT INTO categoria_gramatical (nombre, descripcion, abreviatura, diccionario_id) VALUES
('Sustantivo','Son palabras cuyos referentes son clases de entidades fijas (a diferencia de los pronombres cuyos referentes son contextuales), no estados de hechos o relaciones gramaticales.', 'sust', 1),
('Adjetivo','Es una parte de la oración o clase de palabra que complementa un sustantivo para calificarlo; expresa características o propiedades atribuidas a un sustantivo, ya sean concretas (perceptible por los sentidos, como en el libro grande o the big book) o abstractas (cognoscible por la mente, como en el libro difícil).', 'adj', 1),
('Artículo','Es un tipo de determinante actualizador, una categoría morfológica que emplean algunas lenguas para actualizar o precisar la referencia de un sustantivo, transformándolo de desconocido y abstracto («un libro») a conocido y concreto («el libro»).', 'art', 1),
('Pronombre','Son palabras o morfemas cuyo referente no es fijo sino que se determina en relación con otras que normalmente ya se han nombrado.', 'pron', 1),
('Verbo','Es la parte de la oración o categoría léxica que expresa acción, movimiento, existencia, consecución, condición o estado del sujeto.', 'vrb', 1),
('Adverbio','Es una parte de la oración que complementa a un verbo, un adjetivo, otros adverbios e incluso oraciones. Los adverbios expresan circunstancias, como pueden ser modo, lugar, tiempo, cantidad, afirmación, duda, etc., respondiendo a preguntas como ¿cuándo?, ¿dónde?, ¿cómo?, ¿de qué manera?, entre otras.', 'advrb', 1),
('Interjección','Es una clase de palabras de las lenguas naturales que no constituye una parte de la oración. Equivalen a oraciones que expresan un sentimiento vivo (¡ay!), una llamada enérgica (¡eh!) o describen elementalmente una acción (¡zas!, zigzag) sin ser léxica y gramaticalmente organizadas.', 'intr', 1),
('Preposición','Es la clase de palabra invariable que introduce el llamado sintagma preposicional. Las preposiciones generalmente tienen la función de introducir adjuntos, y en ocasiones también complementos obligatorios ligando el nombre o sintagma nominal al que preceden inmediatamente con un verbo u otro nombre que las antecede.', 'prep', 1),
('Conjunción','Es una palabra o conjunto de ellas que enlaza proposiciones, sintagmas o palabras. Constituye una de las clases de nexos.', 'conj', 1);

INSERT INTO articulo (lema, diccionario_id) VALUES
('a contrapelo',1),
('a destiempo',1),
('a quemarropa',1),
('aún',1),
('abandonado',1),
('blasfemia',1),
('bloque',1),
('bocadillo',1),
('bodega',1),
('braille',1),
('brújula',1),
('charlar',1),
('cheque',1),
('cliente',1),
('clima',1),
('cocer',1);

INSERT INTO acepcion (definicion, prioridad, articulo_id, categoria_gramatical_id, diccionario_id) VALUES
('Contra la inclinación o dirección natural del pelo.',1,1,6,1),
('Contra el curso o modo natural de algo, violentamente.',2,1,6,1),
('Contra el curso o modo natural de algo, violentamente.',1,2,6,1),
('Desde muy cerca.',1,3,6,1),
('De modo brusco y demasiado directo.',2,3,6,1),
('todavía (‖ hasta un momento determinado).',1,4,6,1),
('todavía (‖ no obstante, sin embargo).',2,4,6,1),
('todavía (‖ denota encarecimiento o ponderación).',3,4,6,1),
('Hasta o incluso.',4,4,6,1),
('siquiera (‖ tan solo).',5,4,6,1),
('aunque.',6,4,9,1),
('Descuidado, desidioso.',1,5,2,1),
('Sucio, desaseado.',2,5,2,1),
('Palabra o expresión injuriosas contra alguien o algo sagrado.',1,6,1,1),
('Palabra o expresión gravemente injuriosas contra alguien o algo.',2,6,1,1),
('Trozo grande de un material compacto.',1,7,1,1),
('Pieza compacta en forma de paralelepípedo rectángulo.',2,7,1,1),
('Agrupación generalmente ocasional de partidos políticos, países o asociaciones.',3,7,1,1),
('Pieza de pan abierta, o conjunto de dos rebanadas, en cuyo interior se coloca o se unta algún alimento.',1,8,1,1),
('Refrigerio que los trabajadores y estudiantes suelen tomar entre el desayuno y la comida.',2,8,1,1),
('bocado (‖ porción pequeña de comida).',3,8,1,1),
('Lugar donde se guarda y cría el vino.',1,9,1,1),
('Almacén de vinos.',2,9,1,1),
('Tienda de vinos.',3,9,1,1),
('Sistema de escritura para ciegos que consiste en signos dibujados en relieve para poder leer con los dedos.',1,10,1,1),
('Instrumento consistente en una caja en cuyo interior una aguja imantada gira sobre un eje y señala el norte magnético, que sirve para determinar las direcciones de la superficie terrestre.',1,11,1,1),
('Abertura por donde, entrecerrando los ojos, se mira mejor un objeto.',2,11,1,1),
('En una embarcación, instrumento que indica el rumbo, consistente en una caja, redonda y de bronce, con dos círculos concéntricos, de los cuales solo gira el interior, que lleva la aguja magnética, mientras que el exterior, fijo, lleva señalada la dirección de la quilla del buque.',3,11,1,1),
('Conversar, platicar.',1,12,5,1),
('Hablar mucho, sin sustancia o fuera de propósito.',2,12,5,1),
('parlar (‖ revelar lo que se debe callar).',1,12,5,1),
('Mandato escrito de pago, para cobrar una cantidad determinada de los fondos que quien lo expide tiene disponibles en un banco.',1,13,1,1),
('Usada para expresar asentimiento o conformidad.',2,13,7,1),
('Persona que compra en una tienda, o que utiliza con asiduidad los servicios de un profesional o empresa.',1,14,1,1),
('Persona que está bajo la protección o tutela de otra.',2,14,1,1),
('Conjunto de condiciones atmosféricas que caracterizan una región.',1,15,1,1),
('ambiente (‖ condiciones o circunstancias).',2,15,1,1),
('País, región.',1,15,1,1),
('Hacer comestible un alimento crudo sometiéndolo a ebullición o a la acción del vapor.',1,16,5,1),
('Someter pan, cerámica, piedra caliza, etc., a la acción del calor en un horno, para que pierdan humedad y adquieran determinadas propiedades.',2,16,5,1),
('Someter algo a la acción del fuego en un líquido para que comunique a este ciertas cualidades.',3,16,5,1);

